### ISSUE TITLE
Deployment script proceeds, regarldless of the results of dependencies check

### ISSUE THREAD

**Issue by GigaPrimatus** [Kong/kong-ref-kic-gateway-kind#4]
$ ./redeploy.sh
Checking for Dependencies...
kind ✓
openssl ✓
docker ✓
docker-compose ❌
kubectl ✓
helm ❌
Dependencies not found. Please install and add to path and rerun.
./redeploy.sh: line 29: return: can only `return' from a function or sourced script
./redeploy.sh: line 37: [: too many arguments

All dependencies found.  Deploying Kind and Insalling Kong...

Deleting cluster "multiverse" ...
Deleted nodes: ["multiverse-control-plane"]
./scripts/teardown.sh: line 12: docker-compose: command not found

**Comment by chadningle** [comment]
This happens because it was not run with source.  We use return so that the shell doesn't exit on the person and it needs to be run from source it looks like to work properly. 

`source ./redeploy.sh`

**Comment by GigaPrimatus** [comment]
Got it
